"""create_initial_tables

Revision ID: 001
Revises: 
Create Date: 2025-01-17 01:04:47.794966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_dataset_entities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dev_listings',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dataset_entity_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('image_hashes', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('dev_properties',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('dev_property_values_bool',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['dev_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['dev_properties.property_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'property_id')
    )
    op.create_table('dev_property_values_str',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['dev_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['dev_properties.property_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dev_property_values_str')
    op.drop_table('dev_property_values_bool')
    op.drop_table('dev_properties')
    op.drop_table('dev_listings')
    op.drop_table('dev_dataset_entities')
    # ### end Alembic commands ###
