"""listing_entity_association

Revision ID: 002
Revises: 001
Create Date: 2025-01-20 11:54:04.073846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_entity_association',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['dev_dataset_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['dev_listings.listing_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_entity_association')
    # ### end Alembic commands ###
